import java.lang.reflect.InvocationTargetException;
import javax.swing.SwingUtilities;
import logging.Logger;
import display.Window;
import game.GameBoard;
import game.character.Enemy;
import game.pathfinding.*;
import java.util.*;
import game.MusicPlayer;

class Main {
    private static Window window;

    public static void main(String[] args) {
        processCLIArgs(args);

        Logger.info("Starting game....");
        boolean GAME_RUNNING = true;

        try {
            Logger.info("Creating window...");
            SwingUtilities.invokeAndWait(() -> {
                window = new Window();
                Logger.info("Window created!");
            });

        } catch (InterruptedException | InvocationTargetException e) {
            Logger.error(String.format("Couldn't create window: %s", e.getMessage()));
            GAME_RUNNING = false;
        }

        MusicPlayer musicPlayer = new MusicPlayer();
        musicPlayer.start();

        while (GAME_RUNNING) {
            long time = System.currentTimeMillis();
            window.update(time);
        }
        musicPlayer.stopTrack();
    }

    // Generated by Claude
    public static void processCLIArgs(String[] args) {
        for (int i = 0; i < args.length; i++) {
            if (args[i].equals("--log-level")) {
                if (i + 1 < args.length) {
                    String levelArg = args[i + 1].toUpperCase();
                    Logger.setLevel(levelArg);
                    i++; // Skip the next argument
                } else {
                    System.err.println("Missing argument for --log-level");
                    System.exit(1);
                }
            }
        }
    }
}
