package sprites;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import logging.Logger;
import java.awt.Color;

public class SpriteComponent {
    private boolean useDamageMask = false;
    private BufferedImage spriteSheet;
    private String spriteSheetPath;
    private SpriteSet spriteSet;
    private long animationTimeDeltaMs = 0;
    private long lastUpdateTimeMs = 0;

    public SpriteComponent(String spriteSheetPath, int animationTimeDeltaMs) {
        this.loadSpriteSheet(spriteSheetPath);
        this.spriteSet = new SpriteSet();
        this.animationTimeDeltaMs = animationTimeDeltaMs;
    }

    public SpriteComponent(String spriteSheetPath) {
        this(spriteSheetPath, Integer.MAX_VALUE);
    }

    public void setAnimationTimeDeltaMs(long animationTimeDeltaMs) {
        this.animationTimeDeltaMs = animationTimeDeltaMs;
    }

    public void loadSpriteSheet(String spriteSheetPath) {
        try {
            this.spriteSheet = ImageIO.read(new File(spriteSheetPath));
            Logger.debug("Successfully loaded sprite sheet from " + spriteSheetPath);
            this.spriteSheetPath = spriteSheetPath;
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void updateAnimation(long updateTime) {
        long deltaTime = Math.abs(this.lastUpdateTimeMs - updateTime);

        if (deltaTime > this.animationTimeDeltaMs) {
            Sprite sprite = this.spriteSet.nextSprite();
            this.lastUpdateTimeMs = updateTime;
            this.useDamageMask = false;
        }
    }

    public boolean useDamageMask() {
        return this.useDamageMask;
    }

    public void setUseDamageMask(boolean newVal) {
        this.useDamageMask = newVal;
    }

    // Generated by ChatGPT
    public BufferedImage applyDamageMask(BufferedImage original) {
        // Get the version of the sprite but with all pixels
        // set to red. Useful for demonstrating damage
        int w = original.getWidth();
        int h = original.getHeight();
        BufferedImage out = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);

        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                int argb = original.getRGB(x, y);
                int alpha = (argb >>> 24) & 0xFF;
                if (alpha == 0) {
                    // fully transparent stays transparent
                    out.setRGB(x, y, 0x00000000);
                } else {
                    // keep alpha, replace RGB with your chosen color
                    out.setRGB(x, y, 0xFFFF0000);
                }
            }
        }
        return out;
    }

    public Sprite getNextSprite() {
        Sprite nextSprite = this.spriteSet.getSprite();
        if (this.useDamageMask) {
            Sprite newSprite = new Sprite(nextSprite);
            newSprite.setSpriteSheet(applyDamageMask(newSprite.getSpriteSheet()));
            return newSprite;
        }
        return nextSprite;
    }

    public void loadSprite(int row, int col) {
        this.loadSprite(row, 0, col, 0);
    }

    public void loadSprite(int row, int plus_rows, int col, int plus_cols) {
        /*
         * Loads the sprite at (row, col) on the sprite sheet; each sprite is 1x1 cell on the sheet,
         * unless otherwise specified (i.e. larger multi cell sprite like a building or boat)
         */

        this.spriteSet.addSprite(
                new Sprite(this.spriteSheetPath, this.spriteSheet, row, plus_rows, col, plus_cols));
    }
}

