package input;

import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;

/*
 * Partly generated by ChatGPT.
 */

public class GameKeyListener implements KeyListener {
    private final boolean[] keys = new boolean[256];

    public void keyPressed(KeyEvent e) {
        keys[e.getKeyCode()] = true;
        System.out.println("Got key press: " + e.getKeyCode());
    }

    public void keyReleased(KeyEvent e) {
        keys[e.getKeyCode()] = false;
        System.out.println("Got key release: " + e.getKeyCode());

    }

    public void keyTyped(KeyEvent e) {}
}
