package input;

import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;
import logging.Logger;

/*
 * Partly generated by ChatGPT.
 */

public class GameKeyListener implements KeyListener {
    private final boolean[] keys = new boolean[256]; // all values default to false

    public void keyPressed(KeyEvent e) {
        keys[e.getKeyCode()] = true;
        Logger.debug("Got key press: " + e.getKeyCode());
    }

    public void keyReleased(KeyEvent e) {
        keys[e.getKeyCode()] = false;
        Logger.debug("Got key release: " + e.getKeyCode());
    }

    public void keyTyped(KeyEvent e) {}

    public boolean spacePressed() {
        return keys[KeyCode.SPACE.getCode()];
    }

    public boolean rightArrowPressed() {
        return keys[KeyCode.RIGHT.getCode()];
    }

    public boolean leftArrowPressed() {
        return keys[KeyCode.LEFT.getCode()];
    }

    public boolean downArrowPressed() {
        return keys[KeyCode.DOWN.getCode()];
    }

    public boolean upArrowPressed() {
        return keys[KeyCode.UP.getCode()];
    }
}
